import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { comparePortablePaths, createServiceWorkerCacheName } from "./service-worker-cache.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distRoot = path.join(projectRoot, "dist");

async function listFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await listFiles(fullPath)));
    else if (entry.name !== "sw.js" && !entry.name.startsWith("_")) files.push(fullPath);
  }
  return files;
}

const files = (await listFiles(distRoot))
  .map((fullPath) => ({
    fullPath,
    relativePath: `./${path.relative(distRoot, fullPath).split(path.sep).join("/")}`,
  }))
  .sort((left, right) => comparePortablePaths(left.relativePath, right.relativePath));
const relativeFiles = files.map((file) => file.relativePath);
// Include strategy source, portable paths, lengths, and bytes. A rename-only
// release must receive a new cache so a waiting worker cannot mutate the cache
// used by the active release.
const cacheName = createServiceWorkerCacheName([
  { path: "strategy/generate-sw.mjs", contents: await readFile(fileURLToPath(import.meta.url)) },
  { path: "strategy/service-worker-cache.mjs", contents: await readFile(new URL("./service-worker-cache.mjs", import.meta.url)) },
  ...await Promise.all(files.map(async (file) => ({
    path: file.relativePath,
    contents: await readFile(file.fullPath),
  }))),
]);

const serviceWorker = `/* Generated by scripts/generate-sw.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const APP_SHELL = ${JSON.stringify(relativeFiles, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(APP_SHELL)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("sales-ledger-") && key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      caches.open(CACHE_NAME)
        .then((cache) => cache.match("./index.html", { ignoreVary: true }))
        // Keep this worker's HTML paired with its installed assets. A newer
        // shell becomes active through the existing Update now flow. Do not
        // write network HTML into an older version's cache on a cache miss.
        .then((cached) => cached || fetch(request)),
    );
    return;
  }

  event.respondWith(
    caches.open(CACHE_NAME).then((cache) =>
      cache.match(request, { ignoreVary: true }).then((cached) => cached || fetch(request)),
    ),
  );
});
`;

await writeFile(path.join(distRoot, "sw.js"), serviceWorker, "utf8");
console.log(`Generated ${cacheName} with ${relativeFiles.length} cached files.`);
